---
- name: Disable selinux
  become: yes
  become_method: sudo
  selinux:
    state: disabled

- name: Disable firewalld
  become: yes
  become_method: sudo
  systemd:
    name: firewalld
    state: stopped
    enabled: False

- name: Install docker dependency
  become: yes
  become_method: sudo
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add docker repo
  become: yes
  become_method: sudo
  shell: yum-config-manager --add-repo 'https://download.docker.com/linux/centos/docker-ce.repo'
  args:
    executable: /bin/bash

- name: Install docker
  become: yes
  become_method: sudo
  yum:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Create docker config folder
  become: yes
  become_method: sudo
  file:
    path: /etc/docker
    state: directory

- name: Copy daemon.json
  become: yes
  become_method: sudo
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Start docker
  become: yes
  become_method: sudo
  systemd:
    name: docker
    state: started
    enabled: True

- name: Execute post-install steps
  become: yes
  become_method: sudo
  command: "{{ item }}"
  with_items:
    #- groupadd docker
    - usermod -aG docker "{{ ansible_user }}"
